#!/bin/bash

HOSTNAME=$(hostname)
USERNAME=$(whoami)
DATETIME=$(date)

source /etc/os-release
OS="$NAME $VERSION"

UPTIME=$(uptime -p)
CPU=$(lshw -quiet -class processor 2>/dev/null | awk -F: '/product/ {print $2}' | head -n 1 | xargs)
RAM=$(free -h | awk '/Mem:/ {print $2}')
DISKS=$(lsblk -d -o model,size | grep -E "VMware|ATA|SSD|HDD")
VIDEO=$(lshw -quiet -class display 2>/dev/null | awk -F: '/product/ {print $2}' | head -n 1 | xargs)

DEF_INT=$(ip route | awk '/default/ {print $5; exit}')
HOST_IP=$(ip -4 addr show "$DEF_INT" | awk '/inet / {print $2}' | cut -d/ -f1)
GATEWAY=$(ip route | awk '/default/ {print $3; exit}')
DNS=$(grep -m 1 "nameserver" /etc/resolv.conf | awk '{print $2}')

USERS=$(who | awk '{print $1}' | sort -u | paste -sd "," -)
DISK_SPACE=$(df -h --output=target,avail | tail -n +2)
PROCESS_COUNT=$(ps -e --no-headers | wc -l)
LOAD_AVERAGES=$(awk '{print $1", "$2", "$3}' /proc/loadavg)
PORTS=$(ss -tuln 2>/dev/null | awk 'NR>1 {split($5,a,":"); print a[length(a)]}' | sort -n | uniq | paste -sd "," -)
UFW_STATUS=$(sudo ufw status 2>/dev/null | head -n 1)

echo ""
echo "System Report for $HOSTNAME generated by $USERNAME, on $DATETIME"
echo ""
echo "System Information"
echo "------------------"
echo "OS: $OS"
echo "Uptime: $UPTIME"
echo "CPU: $CPU"
echo "RAM: $RAM"
echo "Disk(s):"
echo "$DISKS"
echo "Video: $VIDEO"
echo "Host Address: $HOST_IP"
echo "Gateway IP: $GATEWAY"
echo "DNS Server: $DNS"
echo ""
echo "System Status"
echo "-------------"
echo "Users Logged In: $USERS"
echo "Disk Space:"
echo "$DISK_SPACE"
echo "Process Count: $PROCESS_COUNT"
echo "Load Averages: $LOAD_AVERAGES"
echo "Listening Network Ports: $PORTS"
echo "UFW Status: $UFW_STATUS"
echo ""

